### ISSUE TITLE
Cancel button broken on fPanel Confirm when no imls present

### ISSUE THREAD

**Issue by sh0shinsha** [ImagArena/native-classroom-client#21]

**Comment by elliotjberman** [comment]
<img width="1112" alt="screen shot 2018-09-19 at 11 03 19 pm" src="https://user-images.githubusercontent.com/9270660/45793462-3a8cfa00-bc60-11e8-863c-c6c05478f110.png">
This worked for me

**Comment by sh0shinsha** [comment]
ok i can clarify.  its an edge case, but if the current level has no imls found, the clicking either button doies escapes the panel window but does nothing beyond that.  its an edge case since there will be no missing imls in the final app, but maybe it points to somethign shadyy

**Comment by elliotjberman** [comment]
Aight I’ll look into it
